name: Release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build and upload source distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    # Comment this line for testing
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build sdist
        run: pipx run build --sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        # Uncomment these lines for testing
        # with:
        #   repository-url: https://test.pypi.org/legacy/
